name: MADEK/zhdk-agw-new
windows:
  2:
    name: app
    command: |
      bundle exec rerun 'bundle exec ruby zhdk-agw-auth-system.rb'
  5:
    name: deploy
    command: |
      # ansible-playbook -i ../madek_v5/zhdk-inventory/staging-hosts -l zhdk-madek-staging deploy/deploy_play.yml --ssh-common-args '-o ProxyCommand="ssh -W %h:%p -q root@ci-gw.zhdk.ch"'
      # ansible-playbook -i ../madek_v5/zhdk-inventory/prod-hosts-v5 deploy/deploy_play.yml --ssh-common-args '-o ProxyCommand="ssh -W %h:%p -q root@ci-gw.zhdk.ch"'
